version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./backend/data:/app/data

# host 模式下不需要定义额外的网络 